# Generated by Django 5.2 on 2026-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ELECTED', 'Elected Official'), ('APPOINTED', 'Appointed Staff')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within their column.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
