# Generated by Django 5.2 on 2026-08-25 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('template_body', models.TextField(help_text='Template text with placeholders, e.g. {{resident.full_name}}')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='documents.documenttype')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to='residents.resident')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
