# Generated by Django 5.2 on 2026-08-31 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddocument',
            name='walk_in_details',
            field=models.JSONField(blank=True, help_text='Manually entered recipient info for a walk-in with no Resident record.', null=True),
        ),
        migrations.AlterField(
            model_name='issueddocument',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to='residents.resident'),
        ),
    ]
