# Generated by Django 5.2 on 2026-08-31 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_issueddocument_walk_in_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddocument',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
