"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%yt9)or35__zpgwrffg=i7k)ymyogue=v_a+$6%j@xdi!oh7lz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # BRMS domain apps
    'accounts',
    'residents',
    'recognition',
    'documents',
    'audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth
# Everything in this system is internal barangay-office tooling behind a
# login wall — there's no public-facing area, so the login redirect target
# is simply "wherever staff work", not a marketing page.
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'residents:resident_list'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Face recognition engine
#
# DeepFace requires TensorFlow, which has no build for the Python version
# this project runs on (3.14, as of writing) -- see recognition/face_engine.py
# for the full explanation. Face extraction runs in a separate interpreter,
# a Python 3.11 environment with DeepFace/TensorFlow installed, invoked as a
# subprocess per photo. FACE_ENGINE_PYTHON points at that interpreter.
#
# Overridable via env var so this doesn't hardcode one developer's home
# directory into a file every contributor's checkout picks up; on the
# eventual Windows/PyInstaller deployment target this will instead point at
# a bundled portable Python, not a conda env.
FACE_ENGINE_PYTHON = os.environ.get(
    'FACE_ENGINE_PYTHON',
    str(Path.home() / 'miniconda3' / 'envs' / 'brms-face' / 'bin' / 'python'),
)
FACE_ENGINE_TIMEOUT = 60  # seconds -- generous because a cold TensorFlow import is slow

# DeepFace's own published threshold for Facenet + cosine distance
# (see deepface.modules.verification.find_threshold). Distances below this
# are considered the same person.
FACE_MATCH_THRESHOLD = 0.40
