"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Local development works with no env vars set. A deployment (see the
# Dockerfile) must set DJANGO_SECRET_KEY and DJANGO_DEBUG=0.
DEBUG = env_bool('DJANGO_DEBUG', True)

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off.')
    SECRET_KEY = 'django-insecure-local-dev-only'

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Public online demo: shows demo credentials on the login page and serves
# uploaded media from Django itself (there's no separate file server).
DEMO_MODE = env_bool('BRMS_DEMO_MODE', False)
DEMO_PASSWORD = os.environ.get('BRMS_DEMO_PASSWORD', 'brms-demo')
SERVE_MEDIA = DEBUG or env_bool('BRMS_SERVE_MEDIA', False)

# Origins allowed to embed the app in an iframe (e.g. the Hugging Face
# Space page). Empty keeps Django's default X-Frame-Options: DENY.
FRAME_ANCESTORS = env_list('BRMS_FRAME_ANCESTORS')

if not DEBUG:
    # The host terminates TLS and forwards plain HTTP to the container.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if FRAME_ANCESTORS:
        # Cookies set inside a cross-site iframe are dropped unless SameSite=None.
        SESSION_COOKIE_SAMESITE = 'None'
        CSRF_COOKIE_SAMESITE = 'None'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # BRMS domain apps
    'accounts',
    'residents',
    'recognition',
    'documents',
    'audit',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Before XFrameOptions so it sees the response after that header is set.
    'core.middleware.FrameAncestorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('BRMS_SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Uploaded, persisted images (core.Official / core.SiteSettings photos) --
# distinct from face-recognition photos, which are deliberately never
# written here or anywhere else (see recognition/face_worker.py).
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('BRMS_MEDIA_ROOT', BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth
# Everything in this system is internal barangay-office tooling behind a
# login wall — there's no public-facing area, so the login redirect target
# is simply "wherever staff work", not a marketing page.
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Face recognition engine
#
# DeepFace requires TensorFlow, which has no build for the Python version
# this project runs on (3.14, as of writing) -- see recognition/face_engine.py
# for the full explanation. Face extraction runs in a separate interpreter,
# a Python 3.11 environment with DeepFace/TensorFlow installed, invoked as a
# subprocess per photo. FACE_ENGINE_PYTHON points at that interpreter.
#
# Overridable via env var so this doesn't hardcode one developer's home
# directory into a file every contributor's checkout picks up; on the
# eventual Windows/PyInstaller deployment target this will instead point at
# a bundled portable Python, not a conda env.
FACE_ENGINE_PYTHON = os.environ.get(
    'FACE_ENGINE_PYTHON',
    str(Path.home() / 'miniconda3' / 'envs' / 'brms-face' / 'bin' / 'python'),
)
FACE_ENGINE_TIMEOUT = int(os.environ.get('FACE_ENGINE_TIMEOUT', 60))  # seconds -- generous because a cold TensorFlow import is slow

# DeepFace's own published threshold for Facenet + cosine distance
# (see deepface.modules.verification.find_threshold). Distances below this
# are considered the same person.
FACE_MATCH_THRESHOLD = 0.40


# Document issuance
# Short code prefixed onto every generated control_number, e.g.
# "BRGY-2026-0001". A placeholder until a specific barangay's real code is
# configured -- overridable via env var rather than hardcoded so this file
# doesn't need editing per deployment.
BARANGAY_CODE = os.environ.get('BARANGAY_CODE', 'BRGY')
